cmake_minimum_required(VERSION 3.22)

message("Building package with pixi : will install glew and zlib header by hands to cope for the absence of the WinDepPack")
find_package(GLEW REQUIRED QUIET)
if(NOT GLEW_FOUND)
    message(WARNING "Cannot find GLEW, its headers will not be installed.")
else()
    get_target_property(glew_incl GLEW::GLEW INTERFACE_INCLUDE_DIRECTORIES)
    if(NOT EXISTS "${glew_incl}/GL/glew.h")
        message(FATAL_ERROR "Didn't find required header GL/glew.h")
    else()
        install(FILES ${glew_incl}/GL/glew.h DESTINATION include/extlibs/GL)
    endif()
endif()

find_package(ZLIB REQUIRED QUIET)
if(NOT ZLIB_FOUND)
    message(WARNING "Cannot find ZLIB, its headers will not be installed.")
else()
    get_target_property(zlib_incl ZLIB::ZLIB INTERFACE_INCLUDE_DIRECTORIES)
    if(NOT EXISTS "${zlib_incl}/zlib.h" OR NOT EXISTS "${zlib_incl}/zconf.h")
        message(FATAL_ERROR "Didn't find required headers zlib.h and zconf.h")
    else()
        install(FILES ${zlib_incl}/zlib.h ${zlib_incl}/zconf.h DESTINATION include/extlibs/)
    endif()
endif()

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/licenses/ DESTINATION licenses COMPONENT applications)
